name: Hexo Deploy

on:
  push:
    branches:
      - main  # 监听主分支push事件

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Generate static files
      run: |
        npx hexo clean
        npx hexo generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./public
        external_repository: alexw914/alexw914.github.io  # 👈 目标仓库
        publish_branch: main                              # 👈 部署到 main 分支
        user_name: github-actions
        user_email: github-actions@github.com
